language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license-c81a61d9'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
