crawler:
  delay: 3600000
  news:
    apikey: "c96e519c4c484966b2929b4177b91749"
    apiurl: "https://newsapi.org/v1/articles"
  instagram:
    apikey: "test"
    apiurl: "test"
extractor:
  article:
    apikey: "fbfOQzeyQ0aXewj3oxJQ1D9zP24QuoBAxejPadhr"
    apiurl: "https://mercury.postlight.com/parser?url="
server:
  port: 8081
management:
  port: 9081
spring:
  data:
    mongodb:
      host: ${MONGO_URL:localhost}
      port: ${MONGO_PORT:27017}