crawler:
  delay: 3600000
  connection:
    connection-request-timeout: 5000
    connect-timeout: 5000
    read-timeout: 5000
  news:
    apikey: "c96e519c4c484966b2929b4177b91749"
    apiurl: "https://newsapi.org/v1/articles"
  instagram:
    apikey: "test"
    apiurl: "test"
  twitter:
    consumerkey: "qTm7lDjrDP07gQONZoYI2ezbO"
    consumersecret: "BLd1QmJGIlaqG7Zqc6YAxmD9hTng1hRBDTca0DyDm2qmOwyJkE"
    accestoken: "846315704735465472-YEAAg8AXPK3VhI5u5Q9iFAqwq4C5lGJ"
    accestokensecret: "wqsD8kZDVa34Ak5bGLKKtsz0ZbYb9CwehgmzRS0TXBrL9"
  quotes:
    delay: 10800000
extractor:
  article:
    apikey: "fbfOQzeyQ0aXewj3oxJQ1D9zP24QuoBAxejPadhr"
    apiurl: "https://mercury.postlight.com/parser?url="
server:
  port: 8081
management:
  port: 9081
  security:
      enabled: false
spring:
  data:
    mongodb:
      host: ${MONGO_URL:localhost}
      port: ${MONGO_PORT:27017}
logging:
  path: /var/log/crawler/
